# file: dask-config.yaml
# author: Jess Robertson CSIRO Mineral Resources
#    (modified lightly from https://github.com/dask/helm-chart/blob/master/dask/values.yaml)
# date: September 2018
#
# description: Spins up a dask cluster for me using helm. To deploy
# see running_dask_gcloud.md. To update your deployment, just do
# `helm upgrade $DEPLOYMENT_NAME stable/dask -f dask-config.yaml`

# Worker config
worker:
  replicas: 6
  resources:
    limits:
      cpu: 1
      memory: 8G
    requests:
      cpu: 1
      memory: 8G
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: gcsfs s3fs dask-ml --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: gcsfs dask-ml --upgrade
